spring:
  cloud:
    zookeeper:
      connect-string: 10.33.107.16:2800
      discovery:
        root: /springcloud-server
        register: false
      dependencies:
        service-zookeeper:
          path: /springcloud-server
          loadBalancerType: ROUND_ROBIN
          required: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: springcloud-client
server:
  port: 6666
  tomcat:
    uri-encoding: utf-8