spring:
  application:
    name: springcloud-server
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.108.63:6606/uc?characterEncoding=UTF-8
    username: qa
logging:
  level:
    com:
      dalaoyang:
        dao:
          UserMapper: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.chenhaibo.model
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 1213
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1212/eureka/